### ISSUE TITLE
..

### ISSUE THREAD

**Issue by harshgitopner** [snigdho611/Electronics-Showroom-Management-System#1]
Sir how should i copy source code and snaps of the screen for my project pls help

**Comment by snigdho611** [comment]
If you have MySQL installed on your system, you can download the whole code and provide it with the proper connection string. Later on, you can run the code yourself and take screenshots for whatever project you are working on. Hope this helps.

**Comment by harshgitopner** [comment]
> If you have MySQL installed on your system, you can download the whole code and provide it with the proper connection string. Later on, you can run the code yourself and take screenshots for whatever project you are working on. Hope this helps.

**Comment by harshgitopner** [comment]
Sir can you pls give your email ,or any other contact media, i have some doubts about it , and thnks for help , it was great of you
